# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b9aa4a5c6b73e125d5d9c2cacf4bf521fdd998ada5b7d05e2e508cddc924613bea8d2a1685d63ff5026d9a7e20d6ae9f8d15c08ce87520a8542c76ac84054232

test:
  secret_key_base: b882b88854189170dae478bba7a615998a8b49247f1ea19175496495acb18bbd43d457bfc704e07f8220d19d61a808d1c9872c240c0cb92ccf5b67958a38962b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
